workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Expo prebuild
        script: |
          npx expo prebuild
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
